insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Schuster-Strosin', 'biz', 'MEX', 'drupal.org', '54479 Coleman Road');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Orn LLC', 'edu', 'MEX', 'geocities.com', '54810 Basil Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Brown Inc', 'com', 'MEX', 'nature.com', '90 Calypso Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Bogisich, Prosacco and Zulauf', 'org', 'MEX', 'comcast.net', '372 Sloan Court');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Marvin-Ritchie', 'gov', 'MEX', 'google.co.uk', '86092 Pearson Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Hickle-Goyette', 'mil', 'MEX', 'nhs.uk', '37 Schmedeman Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Conn-Krajcik', 'biz', 'MEX', 'usnews.com', '5228 Scofield Lane');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Hermann-Treutel', 'org', 'MEX', 'whitehouse.gov', '76 Kensington Place');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Huel-Feil', 'name', 'MEX', 'meetup.com', '262 Grasskamp Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Hills and Sons', 'mil', 'MEX', 'paginegialle.it', '3 Dawn Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Volkman, Hand and Williamson', 'net', 'MEX', 'hud.gov', '44214 Barby Plaza');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Farrell, Bradtke and Collins', 'mil', 'MEX', 'rambler.ru', '34 Rigney Street');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Ankunding Inc', 'com', 'MEX', 'sciencedirect.com', '6533 Sunnyside Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Williamson, Walsh and Jenkins', 'name', 'MEX', 'goo.ne.jp', '8338 Hoffman Place');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Simonis, Hilpert and Gorczany', 'net', 'MEX', 'themeforest.net', '2 Doe Crossing Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Schulist and Sons', 'gov', 'MEX', 'springer.com', '07 Mcguire Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Schulist Group', 'org', 'MEX', 'acquirethisname.com', '4 Meadow Ridge Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Schumm-Schaden', 'net', 'MEX', 'comcast.net', '5343 Pennsylvania Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Ebert-Champlin', 'org', 'MEX', 'phpbb.com', '5400 Grasskamp Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Reilly Inc', 'edu', 'MEX', 'go.com', '47991 John Wall Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Jacobson-Crooks', 'com', 'MEX', 'bing.com', '41 Transport Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Dach-McCullough', 'biz', 'MEX', 'wunderground.com', '3 Longview Lane');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Witting, Botsford and Donnelly', 'info', 'MEX', 'xinhuanet.com', '7867 Bellgrove Pass');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Boyer Group', 'info', 'MEX', 'uol.com.br', '18975 Arkansas Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Tromp-Kreiger', 'mil', 'MEX', 'ovh.net', '18209 Linden Lane');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Heidenreich-Reichel', 'edu', 'MEX', 'examiner.com', '2 Holy Cross Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Botsford and Sons', 'com', 'MEX', 'feedburner.com', '54 Eastlawn Circle');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Mitchell Group', 'biz', 'MEX', 'storify.com', '31 Bunker Hill Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Ledner Inc', 'gov', 'MEX', 'un.org', '03 Morningstar Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Muller LLC', 'name', 'MEX', 'omniture.com', '09115 Anderson Pass');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Parisian-Friesen', 'info', 'MEX', 'i2i.jp', '79260 Mitchell Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Larkin, Grimes and Dicki', 'edu', 'MEX', 'de.vu', '0657 Stang Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Kunze and Sons', 'net', 'MEX', 'bing.com', '430 Sunfield Way');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Steuber Group', 'name', 'MEX', 'furl.net', '510 Dawn Street');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Kub Inc', 'biz', 'MEX', 'stanford.edu', '6 La Follette Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Fay Group', 'com', 'MEX', 'stanford.edu', '6843 Golf View Alley');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Koelpin Group', 'gov', 'MEX', 'usatoday.com', '107 Utah Drive');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Mitchell, Gibson and Erdman', 'mil', 'MEX', 'stumbleupon.com', '3433 Corscot Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Lemke LLC', 'gov', 'MEX', 'deliciousdays.com', '787 Monterey Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Schroeder Group', 'org', 'MEX', 'washington.edu', '588 Nova Alley');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Parker Inc', 'name', 'MEX', 'usda.gov', '2 3rd Alley');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Von, Berge and Klocko', 'info', 'MEX', 'parallels.com', '850 Service Park');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Kiehn, Shanahan and Kemmer', 'org', 'MEX', 'ezinearticles.com', '1 Shoshone Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Macejkovic, Daniel and Schultz', 'info', 'MEX', 'seesaa.net', '2 Susan Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Mertz-Treutel', 'biz', 'MEX', 'baidu.com', '847 Holmberg Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Walker Group', 'name', 'MEX', 'webmd.com', '4 Katie Way');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Hansen LLC', 'mil', 'MEX', 'arizona.edu', '4 Anzinger Place');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Adams, Cartwright and Sanford', 'edu', 'MEX', 'psu.edu', '8 Oak Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Brekke, Koch and Welch', 'info', 'MEX', 'state.tx.us', '54590 Banding Trail');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Quigley and Sons', 'info', 'MEX', 'instagram.com', '0 Doe Crossing Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Halvorson Inc', 'mil', 'MEX', 'macromedia.com', '6182 Fremont Circle');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Effertz LLC', 'mil', 'MEX', 'clickbank.net', '9384 Bultman Drive');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Pollich Inc', 'org', 'MEX', 'taobao.com', '223 Nelson Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Stiedemann, Wiza and Runolfsson', 'name', 'MEX', 'twitter.com', '02 Swallow Drive');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Jaskolski-Barrows', 'info', 'MEX', 'nifty.com', '9 Kipling Pass');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Gibson, Wehner and Emmerich', 'info', 'MEX', 'ow.ly', '47 Rigney Terrace');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Marquardt and Sons', 'mil', 'MEX', 'spotify.com', '3217 Sauthoff Court');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Connelly, Altenwerth and Beahan', 'org', 'MEX', 'huffingtonpost.com', '27722 4th Way');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Koss, Corwin and Bartell', 'net', 'MEX', 'reddit.com', '32005 Banding Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Emard, Schulist and Beier', 'name', 'MEX', 'marketwatch.com', '58 Center Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Cruickshank-Jenkins', 'net', 'MEX', 'unicef.org', '526 Village Green Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Runolfsdottir Group', 'com', 'MEX', 'globo.com', '1 Thompson Place');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Rogahn Inc', 'net', 'MEX', 'netvibes.com', '216 Sunbrook Avenue');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Flatley, Monahan and Bode', 'org', 'MEX', 'boston.com', '12444 Eagle Crest Avenue');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Thompson-Zemlak', 'name', 'MEX', 'weebly.com', '5465 Pepper Wood Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Herman-Balistreri', 'mil', 'MEX', 'eventbrite.com', '4814 Northfield Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Little Inc', 'edu', 'MEX', 'berkeley.edu', '953 Morning Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Labadie, Greenholt and Schumm', 'name', 'MEX', 'cloudflare.com', '40643 Fairfield Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Hettinger Group', 'biz', 'MEX', 'facebook.com', '8148 Pankratz Park');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Stroman, Walker and Krajcik', 'info', 'MEX', 'icio.us', '7975 Rockefeller Terrace');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Muller-Lowe', 'info', 'MEX', 'alexa.com', '9254 Sauthoff Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Connelly, Fritsch and Volkman', 'mil', 'MEX', 'gnu.org', '09917 Kedzie Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Kuvalis, Williamson and Rippin', 'edu', 'MEX', 'theglobeandmail.com', '78550 Goodland Court');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Vandervort Inc', 'info', 'MEX', 'soundcloud.com', '2 Fordem Plaza');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Kertzmann-Russel', 'info', 'MEX', 'privacy.gov.au', '21730 Mariners Cove Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Reynolds, Yundt and Luettgen', 'name', 'MEX', 'mac.com', '781 Clove Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Leannon-Towne', 'name', 'MEX', '1und1.de', '1 Sundown Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Ebert, Skiles and Quitzon', 'net', 'MEX', 'europa.eu', '2 Scofield Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Stroman, Predovic and Weber', 'org', 'MEX', 'edublogs.org', '47 Rutledge Trail');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Johns, Koch and Gleason', 'org', 'MEX', 'yandex.ru', '532 Dakota Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Greenholt-Bartell', 'edu', 'MEX', 'sun.com', '2133 Superior Plaza');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Watsica-Hammes', 'com', 'MEX', 'imageshack.us', '7708 Milwaukee Street');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Koepp Group', 'org', 'MEX', 'jiathis.com', '9 Sauthoff Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Homenick, Littel and Bergstrom', 'biz', 'MEX', 'miibeian.gov.cn', '41249 Roxbury Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Waelchi and Sons', 'info', 'MEX', 'reverbnation.com', '719 David Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Johns-Bechtelar', 'edu', 'MEX', 'wunderground.com', '1 Homewood Road');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Rolfson, Medhurst and Stark', 'edu', 'MEX', 'blinklist.com', '7 Lakeland Alley');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Volkman-Tremblay', 'edu', 'MEX', 'umich.edu', '6415 Mccormick Avenue');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Kertzmann, Grant and Fahey', 'name', 'MEX', 'nih.gov', '08069 Duke Trail');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('O''Conner and Sons', 'biz', 'MEX', 'cam.ac.uk', '04 Onsgard Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Jast, Waters and Quigley', 'com', 'MEX', 'i2i.jp', '795 Nevada Crossing');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Okuneva-Lowe', 'com', 'MEX', 'tripod.com', '09615 Steensland Point');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Hauck, Skiles and Heathcote', 'net', 'MEX', 'unc.edu', '1 Chinook Junction');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Bosco-Ruecker', 'info', 'MEX', 'mac.com', '3577 Nancy Place');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('McDermott, Swift and Kihn', 'biz', 'MEX', 'newyorker.com', '91 Hauk Center');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('O''Reilly, Breitenberg and Beer', 'mil', 'MEX', 'huffingtonpost.com', '09907 Harper Park');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Fay and Sons', 'gov', 'MEX', 'ameblo.jp', '25 Randy Hill');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Pfeffer LLC', 'net', 'MEX', 'webnode.com', '750 Graedel Parkway');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Parisian Group', 'name', 'MEX', 'independent.co.uk', '28086 Portage Street');
insert into biblioteca (nombre, folio, ubi_geografica, pagina_web, direccion) values ('Beier Inc', 'com', 'MEX', 'ehow.com', '00 Buena Vista Hill');
