insert into editorial (clave, nombre, descripcion) values ('65162-762', 'Adelheid Bartod', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into editorial (clave, nombre, descripcion) values ('57520-0154', 'Xymenes Berryann', 'vehicula consequat morbi a ipsum integer a nibh in quis justo');
insert into editorial (clave, nombre, descripcion) values ('36987-2263', 'Ailbert Casier', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');
insert into editorial (clave, nombre, descripcion) values ('76119-1211', 'Jaimie Tidey', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper');
insert into editorial (clave, nombre, descripcion) values ('59614-298', 'Rae Kearton', 'condimentum curabitur in libero ut massa volutpat');
insert into editorial (clave, nombre, descripcion) values ('45963-438', 'Tamqrah Gavini', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis');
insert into editorial (clave, nombre, descripcion) values ('54591-001', 'Rutherford Mayworth', 'parturient montes nascetur ridiculus mus vivamus vestibulum');
insert into editorial (clave, nombre, descripcion) values ('66479-582', 'Sax Le Fleming', 'odio justo sollicitudin ut suscipit a feugiat et eros');
insert into editorial (clave, nombre, descripcion) values ('33342-035', 'Aurilia Maruszewski', 'erat quisque erat eros viverra eget');
insert into editorial (clave, nombre, descripcion) values ('63057-0001', 'Arluene Cluckie', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
insert into editorial (clave, nombre, descripcion) values ('68084-350', 'Bidget Braddock', 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus');
insert into editorial (clave, nombre, descripcion) values ('0703-9526', 'Kippie Infantino', 'diam cras pellentesque volutpat dui maecenas tristique est et tempus');
insert into editorial (clave, nombre, descripcion) values ('17156-615', 'Winnie Cram', 'sed justo pellentesque viverra pede ac diam cras pellentesque');
insert into editorial (clave, nombre, descripcion) values ('62011-0131', 'Jorge Rubega', 'vestibulum vestibulum ante ipsum primis in faucibus');
insert into editorial (clave, nombre, descripcion) values ('49349-547', 'Georgine Jeeves', 'natoque penatibus et magnis dis parturient montes');
insert into editorial (clave, nombre, descripcion) values ('10202-441', 'Merridie Porrett', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into editorial (clave, nombre, descripcion) values ('68693-001', 'Jonathon Sagerson', 'morbi quis tortor id nulla');
insert into editorial (clave, nombre, descripcion) values ('63629-3982', 'Nil Olwen', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into editorial (clave, nombre, descripcion) values ('68788-9781', 'Sela Rosellini', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus');
insert into editorial (clave, nombre, descripcion) values ('41900-100', 'Cirilo MacConchie', 'vel enim sit amet nunc viverra');
insert into editorial (clave, nombre, descripcion) values ('42507-321', 'Miran Gannicleff', 'porta volutpat erat quisque erat');
insert into editorial (clave, nombre, descripcion) values ('55111-730', 'Karlis Cowdroy', 'venenatis turpis enim blandit mi in porttitor pede justo');
insert into editorial (clave, nombre, descripcion) values ('0065-0429', 'Paton Cisson', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget');
insert into editorial (clave, nombre, descripcion) values ('64980-171', 'Velvet Shelmardine', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel');
insert into editorial (clave, nombre, descripcion) values ('59762-0030', 'Tandi Lammenga', 'elit ac nulla sed vel enim sit amet');
insert into editorial (clave, nombre, descripcion) values ('0264-7635', 'Hinze Burns', 'ipsum praesent blandit lacinia erat vestibulum sed magna');
insert into editorial (clave, nombre, descripcion) values ('42507-958', 'Ashby Cleall', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue');
insert into editorial (clave, nombre, descripcion) values ('61589-1812', 'Arin Ranklin', 'odio cras mi pede malesuada in imperdiet et commodo');
insert into editorial (clave, nombre, descripcion) values ('55154-4055', 'Fields Westnage', 'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere');
insert into editorial (clave, nombre, descripcion) values ('49349-937', 'Valentino Grieves', 'dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into editorial (clave, nombre, descripcion) values ('55154-7463', 'Benni Vick', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into editorial (clave, nombre, descripcion) values ('36987-1529', 'Roz Roust', 'luctus cum sociis natoque penatibus et magnis dis');
insert into editorial (clave, nombre, descripcion) values ('61016-0004', 'Dalis Scorrer', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into editorial (clave, nombre, descripcion) values ('0363-0634', 'Chrotoem Voff', 'turpis enim blandit mi in');
insert into editorial (clave, nombre, descripcion) values ('49288-0814', 'Rozina Baytrop', 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
insert into editorial (clave, nombre, descripcion) values ('43353-264', 'Ellie Goalley', 'donec ut dolor morbi vel lectus in');
insert into editorial (clave, nombre, descripcion) values ('36800-441', 'Carroll Cracknell', 'mattis egestas metus aenean fermentum donec ut mauris eget');
insert into editorial (clave, nombre, descripcion) values ('65162-702', 'Monro Klaesson', 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit');
insert into editorial (clave, nombre, descripcion) values ('48951-3122', 'Edith Bricket', 'congue etiam justo etiam pretium iaculis justo in hac habitasse');
insert into editorial (clave, nombre, descripcion) values ('59779-630', 'Glennis Annett', 'etiam vel augue vestibulum rutrum rutrum neque');
insert into editorial (clave, nombre, descripcion) values ('0054-0045', 'Teddy Abel', 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus');
insert into editorial (clave, nombre, descripcion) values ('52125-385', 'Tommy Gerlts', 'libero ut massa volutpat convallis morbi odio odio');
insert into editorial (clave, nombre, descripcion) values ('41250-250', 'Weylin Scandrett', 'risus semper porta volutpat quam');
insert into editorial (clave, nombre, descripcion) values ('55264-007', 'Edythe Champion', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris');
insert into editorial (clave, nombre, descripcion) values ('10578-036', 'Kip Roo', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into editorial (clave, nombre, descripcion) values ('68001-255', 'Marv Yukhtin', 'sollicitudin ut suscipit a feugiat et eros');
insert into editorial (clave, nombre, descripcion) values ('63304-794', 'Jeddy Van Merwe', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into editorial (clave, nombre, descripcion) values ('63029-276', 'Owen Scadden', 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into editorial (clave, nombre, descripcion) values ('59899-002', 'Antonetta Bolino', 'varius ut blandit non interdum in ante vestibulum ante ipsum primis in');
insert into editorial (clave, nombre, descripcion) values ('63629-3343', 'Adi Siddle', 'phasellus id sapien in sapien iaculis');
insert into editorial (clave, nombre, descripcion) values ('49825-724', 'Blanch Taphouse', 'rhoncus mauris enim leo rhoncus sed vestibulum');
insert into editorial (clave, nombre, descripcion) values ('63323-492', 'Kynthia Tremmil', 'lectus aliquam sit amet diam in');
insert into editorial (clave, nombre, descripcion) values ('59779-286', 'Marja Meneux', 'justo lacinia eget tincidunt eget');
insert into editorial (clave, nombre, descripcion) values ('0024-0605', 'Ardine Fairnington', 'dapibus at diam nam tristique tortor');
insert into editorial (clave, nombre, descripcion) values ('0009-7224', 'Donnamarie Neising', 'sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into editorial (clave, nombre, descripcion) values ('55891-001', 'Benjie Corder', 'rhoncus mauris enim leo rhoncus');
insert into editorial (clave, nombre, descripcion) values ('46123-006', 'Shalna Tyres', 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent');
insert into editorial (clave, nombre, descripcion) values ('0008-4117', 'Mohandis Mallaby', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel');
insert into editorial (clave, nombre, descripcion) values ('54868-6290', 'Jordan Imlach', 'nibh in lectus pellentesque at nulla suspendisse potenti');
insert into editorial (clave, nombre, descripcion) values ('52125-714', 'Celestyna Tuffell', 'leo maecenas pulvinar lobortis est phasellus sit amet');
insert into editorial (clave, nombre, descripcion) values ('63739-251', 'Cherey Ash', 'proin risus praesent lectus vestibulum quam');
insert into editorial (clave, nombre, descripcion) values ('49035-195', 'Perren Mounter', 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed');
insert into editorial (clave, nombre, descripcion) values ('49580-2411', 'Harper Louys', 'mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into editorial (clave, nombre, descripcion) values ('36800-700', 'Aubrette Berzen', 'odio porttitor id consequat in consequat ut nulla sed');
insert into editorial (clave, nombre, descripcion) values ('61919-125', 'Leif Franzettoini', 'quam nec dui luctus rutrum nulla tellus');
insert into editorial (clave, nombre, descripcion) values ('48951-4026', 'Maris Dandison', 'tortor id nulla ultrices aliquet maecenas leo');
insert into editorial (clave, nombre, descripcion) values ('24385-274', 'Hilly Samter', 'vivamus in felis eu sapien cursus');
insert into editorial (clave, nombre, descripcion) values ('0904-5458', 'Reese Cowterd', 'commodo vulputate justo in blandit');
insert into editorial (clave, nombre, descripcion) values ('65862-171', 'Roderigo Ganing', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into editorial (clave, nombre, descripcion) values ('67659-079', 'Cris Tweedy', 'accumsan tellus nisi eu orci mauris lacinia sapien quis');
insert into editorial (clave, nombre, descripcion) values ('57664-644', 'Adlai de Villier', 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla');
insert into editorial (clave, nombre, descripcion) values ('17312-021', 'Olga Bes', 'semper est quam pharetra magna ac consequat metus sapien ut');
insert into editorial (clave, nombre, descripcion) values ('0781-5209', 'Meg Milius', 'praesent id massa id nisl venenatis');
insert into editorial (clave, nombre, descripcion) values ('62864-903', 'Arabel Wandrey', 'blandit mi in porttitor pede justo eu massa donec dapibus');
insert into editorial (clave, nombre, descripcion) values ('41190-310', 'Carolus De Filippis', 'erat quisque erat eros viverra eget congue eget semper');
insert into editorial (clave, nombre, descripcion) values ('57955-8300', 'Burch Leadbeatter', 'feugiat non pretium quis lectus suspendisse potenti in');
insert into editorial (clave, nombre, descripcion) values ('55154-9364', 'Lanna Beamiss', 'vulputate nonummy maecenas tincidunt lacus');
insert into editorial (clave, nombre, descripcion) values ('11673-407', 'Milly Burbank', 'quisque porta volutpat erat quisque');
insert into editorial (clave, nombre, descripcion) values ('51655-085', 'Cicely Tansley', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam');
insert into editorial (clave, nombre, descripcion) values ('67046-024', 'Laurianne Washbrook', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus');
insert into editorial (clave, nombre, descripcion) values ('17819-1066', 'Marie-jeanne Pender', 'faucibus cursus urna ut tellus nulla ut erat');
insert into editorial (clave, nombre, descripcion) values ('43598-331', 'Verna Peddar', 'bibendum felis sed interdum venenatis turpis enim blandit mi');
insert into editorial (clave, nombre, descripcion) values ('55154-1398', 'Catharina Monaghan', 'cras non velit nec nisi vulputate nonummy');
insert into editorial (clave, nombre, descripcion) values ('36987-3303', 'Dulcinea Larvin', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id');
insert into editorial (clave, nombre, descripcion) values ('37808-002', 'Meridith Smallsman', 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at');
insert into editorial (clave, nombre, descripcion) values ('45963-294', 'Morlee Paolicchi', 'dui vel nisl duis ac nibh fusce lacus purus aliquet at');
insert into editorial (clave, nombre, descripcion) values ('30142-145', 'Helenka Plampin', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices');
insert into editorial (clave, nombre, descripcion) values ('60760-792', 'Benson Sadlier', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis');
insert into editorial (clave, nombre, descripcion) values ('67510-0058', 'Penny Chazette', 'blandit mi in porttitor pede justo eu massa');
insert into editorial (clave, nombre, descripcion) values ('21695-308', 'Lula Kinchley', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam');
insert into editorial (clave, nombre, descripcion) values ('44523-602', 'Selinda Russam', 'erat volutpat in congue etiam justo etiam pretium iaculis');
insert into editorial (clave, nombre, descripcion) values ('52544-283', 'Aluino Towler', 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id');
insert into editorial (clave, nombre, descripcion) values ('49260-611', 'Rivkah Salthouse', 'sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into editorial (clave, nombre, descripcion) values ('43526-006', 'Rosmunda Muckart', 'mauris morbi non lectus aliquam sit');
insert into editorial (clave, nombre, descripcion) values ('43857-0198', 'Melly Priestner', 'dapibus duis at velit eu est congue elementum in hac habitasse');
insert into editorial (clave, nombre, descripcion) values ('59260-035', 'Vladamir Courvert', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at');
insert into editorial (clave, nombre, descripcion) values ('41167-3006', 'Merralee Saunders', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio');
insert into editorial (clave, nombre, descripcion) values ('10742-8283', 'Sonya Finby', 'ipsum integer a nibh in quis justo');
insert into editorial (clave, nombre, descripcion) values ('25021-201', 'Dag Cleugher', 'augue vestibulum rutrum rutrum neque');
insert into editorial (clave, nombre, descripcion) values ('0781-6041', 'Jordain Perrygo', 'urna pretium nisl ut volutpat sapien');
insert into editorial (clave, nombre, descripcion) values ('54868-5585', 'Eadith Voden', 'vestibulum ante ipsum primis in faucibus orci luctus');
insert into editorial (clave, nombre, descripcion) values ('55714-4426', 'Dasya Ogilby', 'justo maecenas rhoncus aliquam lacus morbi quis');
insert into editorial (clave, nombre, descripcion) values ('52862-016', 'Meggi Tal', 'hac habitasse platea dictumst aliquam augue quam sollicitudin');
insert into editorial (clave, nombre, descripcion) values ('13537-336', 'Cherianne McIlwreath', 'risus auctor sed tristique in tempus sit amet sem fusce consequat nulla');
insert into editorial (clave, nombre, descripcion) values ('14505-488', 'Klara Middle', 'ante nulla justo aliquam quis turpis eget elit');
insert into editorial (clave, nombre, descripcion) values ('0409-1626', 'Jacky Gauch', 'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend');
insert into editorial (clave, nombre, descripcion) values ('41268-002', 'Shae Niche', 'nulla tellus in sagittis dui vel nisl duis');
insert into editorial (clave, nombre, descripcion) values ('0185-0704', 'Noreen Bozward', 'blandit mi in porttitor pede justo eu massa donec dapibus duis at');
insert into editorial (clave, nombre, descripcion) values ('0904-5307', 'Amalia Crombleholme', 'velit donec diam neque vestibulum eget vulputate ut ultrices');
insert into editorial (clave, nombre, descripcion) values ('68016-804', 'Granville Iles', 'congue elementum in hac habitasse');
insert into editorial (clave, nombre, descripcion) values ('49035-460', 'Atalanta Sonier', 'donec dapibus duis at velit eu est congue elementum');
insert into editorial (clave, nombre, descripcion) values ('35356-501', 'Byrle Cann', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque');
insert into editorial (clave, nombre, descripcion) values ('0615-4504', 'Kerri Hawkeswood', 'quam a odio in hac habitasse platea dictumst maecenas ut massa');
insert into editorial (clave, nombre, descripcion) values ('68682-302', 'Shirley Barabich', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula');
insert into editorial (clave, nombre, descripcion) values ('62211-012', 'Onfroi Wragge', 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus');
insert into editorial (clave, nombre, descripcion) values ('0143-9683', 'Nealon Endricci', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla');
insert into editorial (clave, nombre, descripcion) values ('64117-283', 'Marlowe Dreier', 'aliquet ultrices erat tortor sollicitudin');
insert into editorial (clave, nombre, descripcion) values ('0409-5922', 'Sayers Pilfold', 'cursus urna ut tellus nulla ut erat id mauris');
insert into editorial (clave, nombre, descripcion) values ('36987-2016', 'Noble Chang', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra');
insert into editorial (clave, nombre, descripcion) values ('0781-3132', 'Lilas Sainte Paul', 'quisque erat eros viverra eget congue eget semper');
insert into editorial (clave, nombre, descripcion) values ('37012-667', 'Neda Glozman', 'libero rutrum ac lobortis vel dapibus at');
insert into editorial (clave, nombre, descripcion) values ('66116-427', 'Fleur Kabsch', 'commodo vulputate justo in blandit ultrices');
insert into editorial (clave, nombre, descripcion) values ('22840-0039', 'Meridith Fevers', 'consectetuer adipiscing elit proin interdum mauris');
insert into editorial (clave, nombre, descripcion) values ('37808-469', 'Fabe Mourgue', 'maecenas pulvinar lobortis est phasellus sit');
insert into editorial (clave, nombre, descripcion) values ('59779-313', 'Stern Burthom', 'orci eget orci vehicula condimentum curabitur in');
insert into editorial (clave, nombre, descripcion) values ('50436-7066', 'Ibrahim McGragh', 'ultrices posuere cubilia curae nulla dapibus dolor vel');
insert into editorial (clave, nombre, descripcion) values ('51346-027', 'Kirsti Pinkerton', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into editorial (clave, nombre, descripcion) values ('13533-691', 'Donielle Spellesy', 'ut dolor morbi vel lectus in quam fringilla rhoncus');
insert into editorial (clave, nombre, descripcion) values ('0268-0289', 'Teresita Pearn', 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into editorial (clave, nombre, descripcion) values ('53808-0936', 'Martelle Beebis', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel');
insert into editorial (clave, nombre, descripcion) values ('51655-004', 'Luci Dami', 'turpis enim blandit mi in porttitor pede justo eu massa donec');
insert into editorial (clave, nombre, descripcion) values ('36987-1695', 'Abbi Nassey', 'vulputate elementum nullam varius nulla');
insert into editorial (clave, nombre, descripcion) values ('17478-250', 'Daveta Gabala', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida');
insert into editorial (clave, nombre, descripcion) values ('60764-006', 'Glen Scatchar', 'justo etiam pretium iaculis justo');
insert into editorial (clave, nombre, descripcion) values ('65342-1003', 'Manny Stainer', 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci');
insert into editorial (clave, nombre, descripcion) values ('33261-332', 'Lenee Aitken', 'quam a odio in hac habitasse');
insert into editorial (clave, nombre, descripcion) values ('49035-299', 'George Croyser', 'vel est donec odio justo');
insert into editorial (clave, nombre, descripcion) values ('10812-024', 'Maryann Knutton', 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla');
insert into editorial (clave, nombre, descripcion) values ('52125-100', 'Tirrell Occleshaw', 'facilisi cras non velit nec nisi');
insert into editorial (clave, nombre, descripcion) values ('51531-8977', 'Malinda Maypowder', 'et magnis dis parturient montes');
insert into editorial (clave, nombre, descripcion) values ('55154-6879', 'Kaitlynn Brownsea', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into editorial (clave, nombre, descripcion) values ('0031-8724', 'Ashla MacFie', 'habitasse platea dictumst morbi vestibulum velit id');
insert into editorial (clave, nombre, descripcion) values ('51138-107', 'Kamillah Masseo', 'metus arcu adipiscing molestie hendrerit at vulputate vitae');
insert into editorial (clave, nombre, descripcion) values ('24488-034', 'Shane Etherson', 'lacus morbi quis tortor id');
insert into editorial (clave, nombre, descripcion) values ('0310-0281', 'Lindy Povall', 'integer non velit donec diam neque vestibulum eget vulputate ut');
insert into editorial (clave, nombre, descripcion) values ('58980-409', 'Man Reiners', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante');
insert into editorial (clave, nombre, descripcion) values ('0074-3025', 'Daisey Oldred', 'erat eros viverra eget congue eget semper rutrum nulla');
insert into editorial (clave, nombre, descripcion) values ('16110-260', 'Tabbatha Davenall', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into editorial (clave, nombre, descripcion) values ('24236-594', 'Andre Davidavidovics', 'et ultrices posuere cubilia curae nulla dapibus dolor vel');
insert into editorial (clave, nombre, descripcion) values ('58411-154', 'Sylvia Pleaden', 'nec sem duis aliquam convallis');
insert into editorial (clave, nombre, descripcion) values ('68327-003', 'Kinnie Giffin', 'etiam pretium iaculis justo in hac habitasse');
insert into editorial (clave, nombre, descripcion) values ('56062-647', 'Alaine Mollatt', 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis');
insert into editorial (clave, nombre, descripcion) values ('43857-0150', 'Cindra Bercher', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum');
insert into editorial (clave, nombre, descripcion) values ('49035-515', 'Zelig Shervil', 'rhoncus sed vestibulum sit amet cursus id turpis');
insert into editorial (clave, nombre, descripcion) values ('0496-0883', 'Brook Bamber', 'libero ut massa volutpat convallis morbi odio odio elementum');
insert into editorial (clave, nombre, descripcion) values ('36987-2662', 'Harriott Steward', 'purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into editorial (clave, nombre, descripcion) values ('0591-2466', 'Dominga Ison', 'auctor gravida sem praesent id massa id nisl venenatis lacinia');
insert into editorial (clave, nombre, descripcion) values ('51079-460', 'Paulette Dunklee', 'ut volutpat sapien arcu sed');
insert into editorial (clave, nombre, descripcion) values ('16714-401', 'Wells Stollenbeck', 'sapien non mi integer ac neque');
insert into editorial (clave, nombre, descripcion) values ('43857-0330', 'Annadiane Cosin', 'semper sapien a libero nam dui proin leo odio porttitor');
insert into editorial (clave, nombre, descripcion) values ('54868-3857', 'Helenka McGloughlin', 'nonummy integer non velit donec diam neque');
insert into editorial (clave, nombre, descripcion) values ('0409-4179', 'Alejandro Jiras', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into editorial (clave, nombre, descripcion) values ('61314-701', 'Madelene Terbruggen', 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros');
insert into editorial (clave, nombre, descripcion) values ('51393-6666', 'Fabien McKenny', 'cras in purus eu magna vulputate');
insert into editorial (clave, nombre, descripcion) values ('54868-6301', 'Alon Ascough', 'lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into editorial (clave, nombre, descripcion) values ('68828-171', 'Redford Rivelon', 'tristique in tempus sit amet');
insert into editorial (clave, nombre, descripcion) values ('57520-0089', 'Millie Pakeman', 'auctor sed tristique in tempus');
insert into editorial (clave, nombre, descripcion) values ('63187-124', 'Dorie Barter', 'massa donec dapibus duis at velit eu est congue elementum in');
insert into editorial (clave, nombre, descripcion) values ('0069-3150', 'Noe Bareham', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in');
insert into editorial (clave, nombre, descripcion) values ('51346-072', 'Bud Arnaudot', 'venenatis turpis enim blandit mi in porttitor pede justo eu massa donec');
insert into editorial (clave, nombre, descripcion) values ('55910-289', 'Dulcine Axe', 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris');
insert into editorial (clave, nombre, descripcion) values ('49589-103', 'Kellen Dieton', 'faucibus orci luctus et ultrices');
insert into editorial (clave, nombre, descripcion) values ('43406-0152', 'Charline Viles', 'nisi vulputate nonummy maecenas tincidunt lacus at velit');
insert into editorial (clave, nombre, descripcion) values ('59762-1701', 'Gracia Stoven', 'odio condimentum id luctus nec');
insert into editorial (clave, nombre, descripcion) values ('37000-138', 'Bartholomew Delamere', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam');
insert into editorial (clave, nombre, descripcion) values ('17478-932', 'Lianna Ryles', 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet');
insert into editorial (clave, nombre, descripcion) values ('49348-191', 'Leroi Hackett', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into editorial (clave, nombre, descripcion) values ('59958-201', 'Petr Thornham', 'vivamus vestibulum sagittis sapien cum sociis natoque');
insert into editorial (clave, nombre, descripcion) values ('66949-928', 'Conway Cuttings', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac');
insert into editorial (clave, nombre, descripcion) values ('11523-7351', 'Janenna Braney', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique');
insert into editorial (clave, nombre, descripcion) values ('0159-2500', 'Kally Vant', 'fusce consequat nulla nisl nunc');
insert into editorial (clave, nombre, descripcion) values ('66336-878', 'Orelie Tesche', 'nunc commodo placerat praesent blandit nam nulla integer');
insert into editorial (clave, nombre, descripcion) values ('0378-2260', 'Wrennie Giottoi', 'augue vestibulum ante ipsum primis in faucibus orci');
insert into editorial (clave, nombre, descripcion) values ('45802-978', 'Ferdinand Dugdale', 'nullam sit amet turpis elementum');
insert into editorial (clave, nombre, descripcion) values ('0338-3552', 'Erl Killcross', 'convallis tortor risus dapibus augue vel accumsan tellus');
insert into editorial (clave, nombre, descripcion) values ('0093-7116', 'Robenia Broker', 'nulla neque libero convallis eget eleifend luctus');
insert into editorial (clave, nombre, descripcion) values ('66902-015', 'Clarance Willstrop', 'posuere felis sed lacus morbi sem mauris');
insert into editorial (clave, nombre, descripcion) values ('51285-079', 'Josselyn Craw', 'at velit vivamus vel nulla eget eros elementum pellentesque quisque');
insert into editorial (clave, nombre, descripcion) values ('49999-383', 'Dorey Peabody', 'cubilia curae mauris viverra diam vitae');
insert into editorial (clave, nombre, descripcion) values ('54569-3473', 'Tawnya Huyton', 'fusce congue diam id ornare imperdiet sapien urna');
insert into editorial (clave, nombre, descripcion) values ('43913-407', 'Michaeline Searight', 'malesuada in imperdiet et commodo vulputate justo');
insert into editorial (clave, nombre, descripcion) values ('63029-062', 'Lyndsie Ygo', 'sapien varius ut blandit non interdum in ante vestibulum');
insert into editorial (clave, nombre, descripcion) values ('55154-3326', 'Olly Quadrio', 'orci eget orci vehicula condimentum');
insert into editorial (clave, nombre, descripcion) values ('0004-0259', 'Brewer Tetford', 'sed lacus morbi sem mauris laoreet ut rhoncus');
insert into editorial (clave, nombre, descripcion) values ('10056-161', 'Clari Keningley', 'condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into editorial (clave, nombre, descripcion) values ('65044-6722', 'Bendix Geratasch', 'in magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into editorial (clave, nombre, descripcion) values ('10812-102', 'Des Glasgow', 'felis ut at dolor quis odio consequat varius');
insert into editorial (clave, nombre, descripcion) values ('10812-961', 'Kare Mussilli', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel');
insert into editorial (clave, nombre, descripcion) values ('54868-3049', 'Lavinie Sheldrake', 'vivamus in felis eu sapien cursus vestibulum proin eu');
insert into editorial (clave, nombre, descripcion) values ('64117-258', 'Yancy Engelmann', 'amet eleifend pede libero quis orci nullam molestie nibh in');
insert into editorial (clave, nombre, descripcion) values ('64376-812', 'Miles Yoodall', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet');
insert into editorial (clave, nombre, descripcion) values ('63323-478', 'Torrance Allingham', 'eget elit sodales scelerisque mauris');
insert into editorial (clave, nombre, descripcion) values ('37808-162', 'Nicol Kinker', 'amet cursus id turpis integer');
insert into editorial (clave, nombre, descripcion) values ('0496-0749', 'Mord Easum', 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into editorial (clave, nombre, descripcion) values ('61715-050', 'Gnni Peye', 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet');
insert into editorial (clave, nombre, descripcion) values ('58593-782', 'Andrea Moncreif', 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat');
insert into editorial (clave, nombre, descripcion) values ('64193-424', 'Elmo Sculpher', 'in ante vestibulum ante ipsum primis');
insert into editorial (clave, nombre, descripcion) values ('0268-6311', 'Amalea Way', 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into editorial (clave, nombre, descripcion) values ('0173-0809', 'Benjie Thatcher', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into editorial (clave, nombre, descripcion) values ('76250-495', 'Vachel Kernell', 'maecenas tincidunt lacus at velit vivamus vel nulla');
insert into editorial (clave, nombre, descripcion) values ('49967-052', 'Haven Gibke', 'nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium');
insert into editorial (clave, nombre, descripcion) values ('0093-7326', 'Eziechiele Grabert', 'aliquam lacus morbi quis tortor id');
insert into editorial (clave, nombre, descripcion) values ('54575-192', 'Cathe Codling', 'lectus aliquam sit amet diam');
insert into editorial (clave, nombre, descripcion) values ('36800-866', 'Den Allender', 'quam sapien varius ut blandit non interdum');
insert into editorial (clave, nombre, descripcion) values ('21695-048', 'Martguerita Franz', 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris');
insert into editorial (clave, nombre, descripcion) values ('13537-467', 'Barry Noke', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus');
insert into editorial (clave, nombre, descripcion) values ('63354-998', 'Gar O''Regan', 'in faucibus orci luctus et');
insert into editorial (clave, nombre, descripcion) values ('0591-0606', 'Josh Endon', 'id justo sit amet sapien dignissim vestibulum');
insert into editorial (clave, nombre, descripcion) values ('64679-903', 'Clemmy Adamsson', 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet');
insert into editorial (clave, nombre, descripcion) values ('55154-4218', 'Jozef Kleinhaut', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed');
insert into editorial (clave, nombre, descripcion) values ('58593-286', 'Deloria Woofenden', 'mi pede malesuada in imperdiet et commodo vulputate justo in');
insert into editorial (clave, nombre, descripcion) values ('57353-102', 'Koralle Gilyatt', 'at turpis a pede posuere nonummy integer non velit donec diam neque');
insert into editorial (clave, nombre, descripcion) values ('55289-310', 'Anissa Kester', 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into editorial (clave, nombre, descripcion) values ('36987-3010', 'Neala Drife', 'sapien cum sociis natoque penatibus et magnis');
insert into editorial (clave, nombre, descripcion) values ('59779-820', 'Juliann Minerdo', 'orci pede venenatis non sodales');
insert into editorial (clave, nombre, descripcion) values ('24385-403', 'Patin O''Hare', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque');
insert into editorial (clave, nombre, descripcion) values ('0548-5633', 'Petronia Tatum', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat');
insert into editorial (clave, nombre, descripcion) values ('0378-6540', 'Katrinka Nottingam', 'eu orci mauris lacinia sapien quis');
insert into editorial (clave, nombre, descripcion) values ('37000-674', 'Davidde Elderkin', 'porttitor lacus at turpis donec posuere metus vitae');
insert into editorial (clave, nombre, descripcion) values ('24338-656', 'Tades Cordoba', 'amet eleifend pede libero quis orci');
insert into editorial (clave, nombre, descripcion) values ('65121-397', 'Iver McNeigh', 'odio in hac habitasse platea dictumst maecenas');
insert into editorial (clave, nombre, descripcion) values ('63629-3367', 'Tyler McGonnell', 'velit nec nisi vulputate nonummy maecenas tincidunt lacus');
insert into editorial (clave, nombre, descripcion) values ('53014-594', 'Juli Steuhlmeyer', 'quis orci eget orci vehicula condimentum');
insert into editorial (clave, nombre, descripcion) values ('54868-2804', 'Ninon Janaszkiewicz', 'odio curabitur convallis duis consequat dui nec nisi');
insert into editorial (clave, nombre, descripcion) values ('49349-519', 'Goldy Goodwins', 'pede justo eu massa donec dapibus duis at velit eu');
insert into editorial (clave, nombre, descripcion) values ('0378-0731', 'Emelita Barlass', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi');
insert into editorial (clave, nombre, descripcion) values ('60512-6457', 'Doug Maxweell', 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam');
insert into editorial (clave, nombre, descripcion) values ('42291-756', 'Milly Greeve', 'aenean lectus pellentesque eget nunc donec quis orci eget');
insert into editorial (clave, nombre, descripcion) values ('36987-1304', 'Agata Birtles', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into editorial (clave, nombre, descripcion) values ('0220-9023', 'Edythe Elderkin', 'tortor risus dapibus augue vel accumsan tellus nisi eu');
insert into editorial (clave, nombre, descripcion) values ('59078-040', 'Simeon Minett', 'odio condimentum id luctus nec molestie sed justo pellentesque');
insert into editorial (clave, nombre, descripcion) values ('0264-4001', 'Toinette Diperaus', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend');
insert into editorial (clave, nombre, descripcion) values ('54473-212', 'Tomaso Tedstone', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a');
insert into editorial (clave, nombre, descripcion) values ('49738-177', 'Xavier Chase', 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at');
insert into editorial (clave, nombre, descripcion) values ('51672-4108', 'Keefer Bortoli', 'eget eleifend luctus ultricies eu nibh quisque');
insert into editorial (clave, nombre, descripcion) values ('63323-464', 'Hurlee Gregorowicz', 'ipsum aliquam non mauris morbi non lectus');
insert into editorial (clave, nombre, descripcion) values ('52584-035', 'Cornela Kilius', 'aliquet maecenas leo odio condimentum id luctus nec');
insert into editorial (clave, nombre, descripcion) values ('0003-0524', 'Joanie Lownsbrough', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus');
insert into editorial (clave, nombre, descripcion) values ('21695-385', 'Marcile Couldwell', 'adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into editorial (clave, nombre, descripcion) values ('21695-433', 'Cristian Airth', 'ipsum integer a nibh in quis justo maecenas');
insert into editorial (clave, nombre, descripcion) values ('13537-292', 'Batsheva Gavigan', 'integer ac neque duis bibendum morbi non quam nec');
insert into editorial (clave, nombre, descripcion) values ('44597-5605', 'Lester Brammer', 'ac leo pellentesque ultrices mattis');
insert into editorial (clave, nombre, descripcion) values ('62011-0074', 'Xylina Gifkins', 'rhoncus aliquet pulvinar sed nisl nunc');
insert into editorial (clave, nombre, descripcion) values ('37205-112', 'Ruben Flannigan', 'purus sit amet nulla quisque');
insert into editorial (clave, nombre, descripcion) values ('58929-100', 'Veronike Whawell', 'vel enim sit amet nunc viverra');
insert into editorial (clave, nombre, descripcion) values ('42515-001', 'Kalil Gusticke', 'est phasellus sit amet erat');
insert into editorial (clave, nombre, descripcion) values ('68817-134', 'Ronnie Dedden', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et');
insert into editorial (clave, nombre, descripcion) values ('51346-245', 'Christel Inworth', 'eget nunc donec quis orci eget orci vehicula condimentum');
insert into editorial (clave, nombre, descripcion) values ('41163-289', 'Renard Cescot', 'ut erat id mauris vulputate elementum');
insert into editorial (clave, nombre, descripcion) values ('13537-448', 'Leonidas Camis', 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum');
insert into editorial (clave, nombre, descripcion) values ('63739-517', 'Perla Antonsson', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras');
insert into editorial (clave, nombre, descripcion) values ('53808-0848', 'Allsun Buttriss', 'mauris lacinia sapien quis libero nullam');
insert into editorial (clave, nombre, descripcion) values ('63739-046', 'Muhammad Durward', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum');
insert into editorial (clave, nombre, descripcion) values ('63739-455', 'Kailey Blackburn', 'varius ut blandit non interdum in ante');
insert into editorial (clave, nombre, descripcion) values ('54868-4033', 'Stanly MacConnal', 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into editorial (clave, nombre, descripcion) values ('68788-0167', 'Carce Escale', 'augue a suscipit nulla elit ac nulla sed vel enim sit');
insert into editorial (clave, nombre, descripcion) values ('66336-817', 'Bellanca Knifton', 'nec condimentum neque sapien placerat ante nulla justo');
insert into editorial (clave, nombre, descripcion) values ('0071-0806', 'Conni Sharer', 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into editorial (clave, nombre, descripcion) values ('55154-4706', 'Grissel Teresa', 'ut volutpat sapien arcu sed augue');
insert into editorial (clave, nombre, descripcion) values ('0074-3165', 'Sioux Simmonite', 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at');
insert into editorial (clave, nombre, descripcion) values ('43269-762', 'Elyssa Sutherington', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem');
insert into editorial (clave, nombre, descripcion) values ('0363-0190', 'Philippine Cale', 'congue risus semper porta volutpat quam pede lobortis ligula sit amet');
insert into editorial (clave, nombre, descripcion) values ('0924-1805', 'Normand Helmke', 'montes nascetur ridiculus mus etiam vel augue vestibulum');
insert into editorial (clave, nombre, descripcion) values ('64764-046', 'Norrie Chittie', 'semper rutrum nulla nunc purus');
insert into editorial (clave, nombre, descripcion) values ('37808-422', 'Shanta Idney', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into editorial (clave, nombre, descripcion) values ('0338-1135', 'Merrill Littrell', 'porttitor id consequat in consequat ut nulla sed accumsan');
insert into editorial (clave, nombre, descripcion) values ('68788-0523', 'Catherin Haffard', 'et magnis dis parturient montes nascetur ridiculus');
insert into editorial (clave, nombre, descripcion) values ('52959-747', 'Dody Ughelli', 'interdum eu tincidunt in leo maecenas pulvinar');
insert into editorial (clave, nombre, descripcion) values ('40104-261', 'Carlota Minard', 'odio condimentum id luctus nec molestie sed justo');
insert into editorial (clave, nombre, descripcion) values ('51346-054', 'Viv de Glanville', 'placerat ante nulla justo aliquam quis turpis eget');
insert into editorial (clave, nombre, descripcion) values ('13537-363', 'Meg McReynolds', 'rhoncus aliquam lacus morbi quis tortor');
insert into editorial (clave, nombre, descripcion) values ('13668-013', 'Rowan Penfold', 'massa quis augue luctus tincidunt nulla');
insert into editorial (clave, nombre, descripcion) values ('57237-002', 'Idalina Basley', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into editorial (clave, nombre, descripcion) values ('33992-0107', 'Isahella Roelofsen', 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum');
insert into editorial (clave, nombre, descripcion) values ('52125-568', 'Maurise Longea', 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien');
insert into editorial (clave, nombre, descripcion) values ('55312-960', 'Ealasaid Frankom', 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into editorial (clave, nombre, descripcion) values ('55910-232', 'Carly Ruprechter', 'id consequat in consequat ut nulla');
insert into editorial (clave, nombre, descripcion) values ('63354-624', 'Cullin Rickerd', 'viverra pede ac diam cras');
insert into editorial (clave, nombre, descripcion) values ('39765-003', 'Gretchen Castles', 'morbi non lectus aliquam sit amet diam in');
insert into editorial (clave, nombre, descripcion) values ('0904-5891', 'Erhart Housegoe', 'diam in magna bibendum imperdiet');
insert into editorial (clave, nombre, descripcion) values ('67544-154', 'Elihu Roggerone', 'luctus cum sociis natoque penatibus');
insert into editorial (clave, nombre, descripcion) values ('54575-397', 'Kellia Glastonbury', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis');
insert into editorial (clave, nombre, descripcion) values ('41520-410', 'Crawford Gabby', 'proin eu mi nulla ac enim in tempor turpis');
insert into editorial (clave, nombre, descripcion) values ('53329-946', 'Abner Ribbon', 'consequat ut nulla sed accumsan');
insert into editorial (clave, nombre, descripcion) values ('0378-9102', 'Judd Eynaud', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed');
insert into editorial (clave, nombre, descripcion) values ('53808-0367', 'Ruthanne Janota', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into editorial (clave, nombre, descripcion) values ('55154-4621', 'Leeanne Shaplin', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis');
insert into editorial (clave, nombre, descripcion) values ('36987-1853', 'Margarita Bedle', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum');
insert into editorial (clave, nombre, descripcion) values ('21749-975', 'Demetria Tinner', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into editorial (clave, nombre, descripcion) values ('50436-4694', 'Alvis Dows', 'ut suscipit a feugiat et eros vestibulum ac est lacinia');
insert into editorial (clave, nombre, descripcion) values ('57664-212', 'Felicle Gandy', 'proin at turpis a pede posuere nonummy');
insert into editorial (clave, nombre, descripcion) values ('48951-1186', 'Karel Djorvic', 'vitae quam suspendisse potenti nullam porttitor lacus');
insert into editorial (clave, nombre, descripcion) values ('11673-910', 'Augustina Rigmand', 'suscipit nulla elit ac nulla sed vel enim');
insert into editorial (clave, nombre, descripcion) values ('41520-530', 'Blythe Shewen', 'tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into editorial (clave, nombre, descripcion) values ('0517-3120', 'Tull Emanuelov', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie');
insert into editorial (clave, nombre, descripcion) values ('0378-6164', 'Renie Watson', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into editorial (clave, nombre, descripcion) values ('0904-5304', 'Rosamond Gherarducci', 'vel enim sit amet nunc viverra dapibus nulla');
insert into editorial (clave, nombre, descripcion) values ('63323-180', 'Welbie Basnall', 'ut volutpat sapien arcu sed augue aliquam');
insert into editorial (clave, nombre, descripcion) values ('54569-6362', 'Ceil Slopier', 'pulvinar sed nisl nunc rhoncus dui');
insert into editorial (clave, nombre, descripcion) values ('10019-106', 'Drona Filippone', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio');
insert into editorial (clave, nombre, descripcion) values ('49349-586', 'Truman Mayger', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into editorial (clave, nombre, descripcion) values ('0075-2450', 'Karon Bakster', 'erat eros viverra eget congue eget');
insert into editorial (clave, nombre, descripcion) values ('30805-003', 'Bennie Jenkyn', 'vestibulum sagittis sapien cum sociis natoque penatibus');
insert into editorial (clave, nombre, descripcion) values ('0268-1373', 'Katee Pennini', 'convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into editorial (clave, nombre, descripcion) values ('63629-4525', 'Isabella Durie', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into editorial (clave, nombre, descripcion) values ('61957-1047', 'Vito Yarranton', 'a nibh in quis justo maecenas rhoncus');
insert into editorial (clave, nombre, descripcion) values ('49349-235', 'Carleen Parvin', 'magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into editorial (clave, nombre, descripcion) values ('66353-100', 'Kippy Castanie', 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into editorial (clave, nombre, descripcion) values ('61722-067', 'Tam Alpin', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into editorial (clave, nombre, descripcion) values ('54305-221', 'Chlo Gemlett', 'velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into editorial (clave, nombre, descripcion) values ('42549-495', 'Rossy Firpi', 'diam vitae quam suspendisse potenti nullam porttitor lacus');
insert into editorial (clave, nombre, descripcion) values ('46123-017', 'Clemente Thyer', 'duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into editorial (clave, nombre, descripcion) values ('52667-004', 'Brody Snary', 'nec sem duis aliquam convallis nunc');
insert into editorial (clave, nombre, descripcion) values ('55301-370', 'Jaymie Tolputt', 'iaculis justo in hac habitasse platea');
insert into editorial (clave, nombre, descripcion) values ('57344-092', 'Koenraad Seefeldt', 'at velit vivamus vel nulla eget eros elementum');
insert into editorial (clave, nombre, descripcion) values ('0781-5221', 'Starlin Filipczak', 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in');
insert into editorial (clave, nombre, descripcion) values ('63824-182', 'Roma McMeekan', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio');
insert into editorial (clave, nombre, descripcion) values ('0009-0796', 'Kain Bowmaker', 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis');
insert into editorial (clave, nombre, descripcion) values ('54569-1697', 'Bettine Rumens', 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas');
insert into editorial (clave, nombre, descripcion) values ('11822-4530', 'Lannie Jennens', 'mi pede malesuada in imperdiet et commodo vulputate justo');
insert into editorial (clave, nombre, descripcion) values ('61995-2825', 'Yetta Siberry', 'vivamus metus arcu adipiscing molestie');
insert into editorial (clave, nombre, descripcion) values ('54973-0603', 'Humfried Blakeman', 'quis augue luctus tincidunt nulla mollis molestie');
insert into editorial (clave, nombre, descripcion) values ('59503-0544', 'Hildegaard McCarney', 'risus auctor sed tristique in');
insert into editorial (clave, nombre, descripcion) values ('13537-407', 'Terrie Palluschek', 'sollicitudin mi sit amet lobortis');
insert into editorial (clave, nombre, descripcion) values ('49781-011', 'Brear Braybrooke', 'quam pede lobortis ligula sit amet eleifend pede libero');
insert into editorial (clave, nombre, descripcion) values ('54569-1729', 'Vasili Burtwhistle', 'volutpat convallis morbi odio odio elementum eu interdum eu');
insert into editorial (clave, nombre, descripcion) values ('60512-6643', 'Armando Studeart', 'nam congue risus semper porta volutpat quam pede lobortis ligula sit');
insert into editorial (clave, nombre, descripcion) values ('63629-1609', 'Nicoline Wells', 'pede malesuada in imperdiet et commodo vulputate');
insert into editorial (clave, nombre, descripcion) values ('59779-132', 'Alon Feechan', 'cubilia curae nulla dapibus dolor vel est');
insert into editorial (clave, nombre, descripcion) values ('54868-6051', 'Nanci Blessed', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into editorial (clave, nombre, descripcion) values ('63044-632', 'Peyter Fossord', 'lectus pellentesque at nulla suspendisse potenti');
insert into editorial (clave, nombre, descripcion) values ('36987-2532', 'Jordain Imlen', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra');
insert into editorial (clave, nombre, descripcion) values ('52125-452', 'Maggee Mazdon', 'consequat morbi a ipsum integer a nibh');
insert into editorial (clave, nombre, descripcion) values ('37808-110', 'Rex Caddy', 'odio odio elementum eu interdum eu tincidunt in leo');
insert into editorial (clave, nombre, descripcion) values ('55312-698', 'Donnell Sobey', 'proin at turpis a pede posuere nonummy integer non velit donec');
insert into editorial (clave, nombre, descripcion) values ('55154-4563', 'Bing Gerritsma', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into editorial (clave, nombre, descripcion) values ('67296-0378', 'Albina McKeran', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into editorial (clave, nombre, descripcion) values ('51079-796', 'Demetris Sapsford', 'lobortis ligula sit amet eleifend pede libero quis orci');
insert into editorial (clave, nombre, descripcion) values ('58214-100', 'Leshia Airlie', 'nunc purus phasellus in felis');
insert into editorial (clave, nombre, descripcion) values ('62584-265', 'Filmore Gehring', 'vulputate justo in blandit ultrices enim lorem ipsum dolor');
insert into editorial (clave, nombre, descripcion) values ('61010-7000', 'Abba Leopold', 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh');
insert into editorial (clave, nombre, descripcion) values ('36987-1630', 'Cicely Skyner', 'commodo vulputate justo in blandit');
insert into editorial (clave, nombre, descripcion) values ('55154-6668', 'Courtnay Doggrell', 'non velit nec nisi vulputate nonummy');
insert into editorial (clave, nombre, descripcion) values ('0173-0720', 'Selig Dodshon', 'justo aliquam quis turpis eget elit sodales');
insert into editorial (clave, nombre, descripcion) values ('40046-0038', 'Millisent Verissimo', 'a libero nam dui proin leo odio porttitor id');
insert into editorial (clave, nombre, descripcion) values ('63645-140', 'Constantine Moreinu', 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea');
insert into editorial (clave, nombre, descripcion) values ('43063-518', 'Nicko Markovic', 'hac habitasse platea dictumst etiam faucibus cursus urna ut');
insert into editorial (clave, nombre, descripcion) values ('50051-0012', 'Kelbee Momery', 'morbi vestibulum velit id pretium iaculis');
insert into editorial (clave, nombre, descripcion) values ('68084-554', 'Raquel Povall', 'in faucibus orci luctus et');
insert into editorial (clave, nombre, descripcion) values ('24208-503', 'Linette Clemetts', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui');
insert into editorial (clave, nombre, descripcion) values ('57955-6235', 'Fernandina Somerlie', 'erat tortor sollicitudin mi sit amet lobortis sapien');
insert into editorial (clave, nombre, descripcion) values ('55910-988', 'Gabrila Farn', 'aliquet massa id lobortis convallis tortor risus dapibus augue');
insert into editorial (clave, nombre, descripcion) values ('54575-113', 'Nariko Ryburn', 'erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into editorial (clave, nombre, descripcion) values ('63323-349', 'Daisi Greatbach', 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into editorial (clave, nombre, descripcion) values ('45963-461', 'Shirline Akers', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into editorial (clave, nombre, descripcion) values ('24571-103', 'Milly Clarabut', 'morbi porttitor lorem id ligula');
insert into editorial (clave, nombre, descripcion) values ('33992-8802', 'Tanhya Garrad', 'proin leo odio porttitor id');
insert into editorial (clave, nombre, descripcion) values ('43063-057', 'Vikki Sore', 'turpis nec euismod scelerisque quam');
insert into editorial (clave, nombre, descripcion) values ('44224-2000', 'Abe Gwynn', 'nullam varius nulla facilisi cras non velit');
insert into editorial (clave, nombre, descripcion) values ('41250-816', 'Sid Cleyburn', 'duis consequat dui nec nisi');
insert into editorial (clave, nombre, descripcion) values ('66949-880', 'Gayler Kinnerley', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into editorial (clave, nombre, descripcion) values ('0172-4960', 'Orrin Hoyt', 'in faucibus orci luctus et ultrices posuere cubilia');
insert into editorial (clave, nombre, descripcion) values ('49527-997', 'Chiquita Ledford', 'sit amet lobortis sapien sapien');
insert into editorial (clave, nombre, descripcion) values ('43846-0021', 'Anselma Gooding', 'vulputate nonummy maecenas tincidunt lacus at velit');
insert into editorial (clave, nombre, descripcion) values ('44206-454', 'Valida McGuane', 'mi integer ac neque duis bibendum morbi non quam nec dui luctus');
insert into editorial (clave, nombre, descripcion) values ('63323-259', 'Kassandra Boarer', 'massa volutpat convallis morbi odio odio elementum');
insert into editorial (clave, nombre, descripcion) values ('0228-2027', 'Amabelle Willford', 'massa id nisl venenatis lacinia aenean sit amet');
insert into editorial (clave, nombre, descripcion) values ('57520-0366', 'Dewitt Scoffham', 'rutrum nulla tellus in sagittis dui vel nisl duis ac nibh');
insert into editorial (clave, nombre, descripcion) values ('54868-4378', 'Justine Mc Curlye', 'tempor convallis nulla neque libero convallis eget eleifend luctus');
insert into editorial (clave, nombre, descripcion) values ('0228-3503', 'Estelle Stroder', 'rutrum nulla tellus in sagittis dui vel nisl duis ac');
insert into editorial (clave, nombre, descripcion) values ('42998-963', 'Binny Giraudy', 'semper est quam pharetra magna ac');
insert into editorial (clave, nombre, descripcion) values ('60782-001', 'Hilton Andreotti', 'ligula sit amet eleifend pede libero quis orci nullam');
insert into editorial (clave, nombre, descripcion) values ('28623-250', 'Binky Spensley', 'sit amet lobortis sapien sapien non');
insert into editorial (clave, nombre, descripcion) values ('36987-1511', 'Wright Spoure', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into editorial (clave, nombre, descripcion) values ('63629-3177', 'Jude Gethin', 'tristique est et tempus semper est quam');
insert into editorial (clave, nombre, descripcion) values ('55154-5063', 'Elie Kinkead', 'ut volutpat sapien arcu sed augue aliquam erat volutpat in');
insert into editorial (clave, nombre, descripcion) values ('0591-2715', 'Camile Hubball', 'ipsum integer a nibh in quis justo maecenas rhoncus');
insert into editorial (clave, nombre, descripcion) values ('52257-1200', 'Percy Ravilious', 'morbi a ipsum integer a nibh in quis justo maecenas');
insert into editorial (clave, nombre, descripcion) values ('53808-0921', 'Kaylee Prazor', 'suspendisse potenti nullam porttitor lacus');
insert into editorial (clave, nombre, descripcion) values ('68084-389', 'Howie Yokel', 'metus vitae ipsum aliquam non');
insert into editorial (clave, nombre, descripcion) values ('16590-867', 'Gorden Skene', 'tempus vel pede morbi porttitor lorem');
insert into editorial (clave, nombre, descripcion) values ('36987-2298', 'Griswold Edensor', 'lacinia nisi venenatis tristique fusce congue diam');
insert into editorial (clave, nombre, descripcion) values ('44924-101', 'Gav Osboldstone', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into editorial (clave, nombre, descripcion) values ('68428-090', 'Kathe Lucks', 'quis orci nullam molestie nibh in lectus pellentesque at');
insert into editorial (clave, nombre, descripcion) values ('48951-8052', 'Tresa Kirton', 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi');
insert into editorial (clave, nombre, descripcion) values ('36987-2449', 'Clarabelle Ottewell', 'in imperdiet et commodo vulputate justo');
insert into editorial (clave, nombre, descripcion) values ('57520-0052', 'Lyndell Semor', 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero');
insert into editorial (clave, nombre, descripcion) values ('0395-4209', 'Torr Burchard', 'ac tellus semper interdum mauris ullamcorper purus sit');
insert into editorial (clave, nombre, descripcion) values ('0472-1262', 'Mahala Lugton', 'ultrices mattis odio donec vitae');
insert into editorial (clave, nombre, descripcion) values ('50964-050', 'Allx Catenot', 'aenean lectus pellentesque eget nunc donec quis orci eget');
insert into editorial (clave, nombre, descripcion) values ('64376-649', 'Charin Isakov', 'gravida nisi at nibh in hac habitasse platea dictumst aliquam');
insert into editorial (clave, nombre, descripcion) values ('61314-245', 'Nell Ubach', 'in faucibus orci luctus et ultrices posuere cubilia');
insert into editorial (clave, nombre, descripcion) values ('51138-060', 'Juan Hattam', 'vestibulum sit amet cursus id turpis integer aliquet');
insert into editorial (clave, nombre, descripcion) values ('61912-001', 'Aviva Garvan', 'nulla sed accumsan felis ut at');
insert into editorial (clave, nombre, descripcion) values ('68180-281', 'Aime Tongs', 'justo pellentesque viverra pede ac diam');
insert into editorial (clave, nombre, descripcion) values ('0006-0711', 'Bevvy Monier', 'non quam nec dui luctus rutrum nulla tellus in sagittis dui');
insert into editorial (clave, nombre, descripcion) values ('63629-4601', 'Mic Fayne', 'justo eu massa donec dapibus duis at velit eu');
insert into editorial (clave, nombre, descripcion) values ('11523-0435', 'Timmie Keedwell', 'faucibus cursus urna ut tellus nulla ut');
insert into editorial (clave, nombre, descripcion) values ('65044-1214', 'Stearne Rae', 'ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into editorial (clave, nombre, descripcion) values ('62045-6333', 'Jim Matthensen', 'velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into editorial (clave, nombre, descripcion) values ('59896-682', 'Matthew Gilkes', 'risus auctor sed tristique in tempus sit amet sem fusce consequat');
insert into editorial (clave, nombre, descripcion) values ('59779-623', 'Bobbye Bortolomei', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into editorial (clave, nombre, descripcion) values ('51138-039', 'El Jira', 'non mauris morbi non lectus aliquam');
insert into editorial (clave, nombre, descripcion) values ('98132-715', 'Delmer Baumadier', 'nunc vestibulum ante ipsum primis in faucibus');
insert into editorial (clave, nombre, descripcion) values ('68645-210', 'Goldie Hembling', 'cubilia curae duis faucibus accumsan');
insert into editorial (clave, nombre, descripcion) values ('43742-0296', 'Christian Frowen', 'id nisl venenatis lacinia aenean sit amet justo morbi');
insert into editorial (clave, nombre, descripcion) values ('64764-301', 'Gwyn Mathe', 'sit amet consectetuer adipiscing elit');
insert into editorial (clave, nombre, descripcion) values ('55714-4503', 'Rosanne Ivantsov', 'tincidunt eu felis fusce posuere');
insert into editorial (clave, nombre, descripcion) values ('68084-484', 'Allene MacLaverty', 'etiam pretium iaculis justo in');
insert into editorial (clave, nombre, descripcion) values ('60681-2705', 'Portie Maypole', 'luctus nec molestie sed justo pellentesque');
insert into editorial (clave, nombre, descripcion) values ('49349-003', 'Gert Freschini', 'proin eu mi nulla ac enim in');
insert into editorial (clave, nombre, descripcion) values ('11344-663', 'Rudyard Spong', 'sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into editorial (clave, nombre, descripcion) values ('0268-1503', 'Elisabetta Sebrook', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum');
insert into editorial (clave, nombre, descripcion) values ('50845-0016', 'Lowell Webland', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis');
insert into editorial (clave, nombre, descripcion) values ('49349-743', 'Prescott Greenstreet', 'diam erat fermentum justo nec condimentum');
insert into editorial (clave, nombre, descripcion) values ('54868-6278', 'Redford Hebborn', 'enim in tempor turpis nec');
insert into editorial (clave, nombre, descripcion) values ('36987-3074', 'Carmel Dannett', 'donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into editorial (clave, nombre, descripcion) values ('24653-801', 'Dyane Simo', 'porta volutpat erat quisque erat eros viverra eget congue');
insert into editorial (clave, nombre, descripcion) values ('63629-2873', 'Cynde Itzakson', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into editorial (clave, nombre, descripcion) values ('55038-555', 'Judd Hazael', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus');
insert into editorial (clave, nombre, descripcion) values ('13668-002', 'Rae Bryceson', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et');
insert into editorial (clave, nombre, descripcion) values ('58930-030', 'Tabb O''Henehan', 'lorem id ligula suspendisse ornare consequat lectus in est');
insert into editorial (clave, nombre, descripcion) values ('49349-232', 'Celeste Raggett', 'eget eleifend luctus ultricies eu nibh quisque id justo sit');
insert into editorial (clave, nombre, descripcion) values ('41163-057', 'Eirena Cropper', 'nulla sed accumsan felis ut at dolor quis odio');
insert into editorial (clave, nombre, descripcion) values ('43742-0185', 'Tabitha Marcos', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into editorial (clave, nombre, descripcion) values ('0363-1262', 'Geraldine Tournie', 'orci luctus et ultrices posuere cubilia curae');
insert into editorial (clave, nombre, descripcion) values ('67046-272', 'Urson D''Antuoni', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into editorial (clave, nombre, descripcion) values ('13668-022', 'Winslow Crispin', 'rutrum nulla nunc purus phasellus in felis donec semper');
insert into editorial (clave, nombre, descripcion) values ('64990-601', 'Hoyt Dobbison', 'ultrices erat tortor sollicitudin mi');
insert into editorial (clave, nombre, descripcion) values ('51079-778', 'Barrie Dohr', 'sapien non mi integer ac neque duis');
insert into editorial (clave, nombre, descripcion) values ('0781-5893', 'Pauly Apted', 'molestie nibh in lectus pellentesque at nulla suspendisse');
insert into editorial (clave, nombre, descripcion) values ('13734-118', 'Raffaello Abry', 'nulla nunc purus phasellus in felis donec semper sapien a libero');
insert into editorial (clave, nombre, descripcion) values ('30142-236', 'Stacy Biernat', 'pellentesque eget nunc donec quis orci eget');
insert into editorial (clave, nombre, descripcion) values ('16590-469', 'Garnet Mooney', 'sagittis nam congue risus semper porta volutpat');
insert into editorial (clave, nombre, descripcion) values ('0310-0134', 'Rebecka MacIlhagga', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel');
insert into editorial (clave, nombre, descripcion) values ('61604-9068', 'Sancho Pennycook', 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis');
insert into editorial (clave, nombre, descripcion) values ('52731-7009', 'Cally Conniam', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into editorial (clave, nombre, descripcion) values ('24208-485', 'Jerrie Fishly', 'magnis dis parturient montes nascetur ridiculus mus etiam');
insert into editorial (clave, nombre, descripcion) values ('55758-002', 'Joela Kinnon', 'turpis nec euismod scelerisque quam');
insert into editorial (clave, nombre, descripcion) values ('50991-578', 'Kriste Winram', 'sapien placerat ante nulla justo');
insert into editorial (clave, nombre, descripcion) values ('50383-740', 'Hubie Castelain', 'lectus aliquam sit amet diam in magna');
insert into editorial (clave, nombre, descripcion) values ('31722-419', 'Adela Gillbee', 'odio consequat varius integer ac leo pellentesque');
insert into editorial (clave, nombre, descripcion) values ('57896-681', 'Sophi Inchboard', 'diam cras pellentesque volutpat dui maecenas tristique');
insert into editorial (clave, nombre, descripcion) values ('0591-0487', 'Barbey Ebrall', 'pede justo lacinia eget tincidunt eget tempus vel pede');
insert into editorial (clave, nombre, descripcion) values ('55316-047', 'Sydney Wicklen', 'duis bibendum morbi non quam nec dui luctus');
insert into editorial (clave, nombre, descripcion) values ('37808-202', 'Nanine Clegg', 'dui vel nisl duis ac');
insert into editorial (clave, nombre, descripcion) values ('59779-135', 'Mycah Credland', 'dolor sit amet consectetuer adipiscing elit');
insert into editorial (clave, nombre, descripcion) values ('54973-2916', 'Evelina Phlippi', 'porttitor id consequat in consequat');
insert into editorial (clave, nombre, descripcion) values ('42851-155', 'Casie Rodrig', 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean');
insert into editorial (clave, nombre, descripcion) values ('54738-905', 'Alfred Danilyak', 'rutrum rutrum neque aenean auctor gravida sem praesent id massa');
insert into editorial (clave, nombre, descripcion) values ('63304-162', 'Marcellus McClean', 'molestie hendrerit at vulputate vitae');
insert into editorial (clave, nombre, descripcion) values ('10742-8458', 'Adena Neale', 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis');
insert into editorial (clave, nombre, descripcion) values ('0268-0931', 'Kerrill Trundell', 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris');
insert into editorial (clave, nombre, descripcion) values ('65044-0825', 'Hashim Barendtsen', 'in porttitor pede justo eu massa donec dapibus');
insert into editorial (clave, nombre, descripcion) values ('55910-025', 'Tull Banbury', 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas');
insert into editorial (clave, nombre, descripcion) values ('67046-227', 'Emmey Valasek', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo');
insert into editorial (clave, nombre, descripcion) values ('36987-1594', 'Lil Coleford', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus');
insert into editorial (clave, nombre, descripcion) values ('51393-7334', 'Cullie Haskur', 'lacus morbi quis tortor id nulla ultrices');
insert into editorial (clave, nombre, descripcion) values ('41520-136', 'Billye Spurdon', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis');
insert into editorial (clave, nombre, descripcion) values ('10596-400', 'Queenie Vondracek', 'pretium iaculis justo in hac');
insert into editorial (clave, nombre, descripcion) values ('67425-003', 'Cassandry Wolfer', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus');
insert into editorial (clave, nombre, descripcion) values ('0054-0221', 'Aguste Grzegorecki', 'nunc vestibulum ante ipsum primis');
insert into editorial (clave, nombre, descripcion) values ('51143-403', 'Eal Hannigan', 'morbi a ipsum integer a nibh in quis justo maecenas');
insert into editorial (clave, nombre, descripcion) values ('55111-284', 'Wanids Rotlauf', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis');
insert into editorial (clave, nombre, descripcion) values ('21695-025', 'Sean Creighton', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at');
insert into editorial (clave, nombre, descripcion) values ('36800-720', 'Tiphany Zeal', 'rutrum neque aenean auctor gravida');
insert into editorial (clave, nombre, descripcion) values ('50111-456', 'Donella Darcey', 'nisl nunc nisl duis bibendum felis sed interdum venenatis');
insert into editorial (clave, nombre, descripcion) values ('0781-7117', 'Marjy Gland', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into editorial (clave, nombre, descripcion) values ('13107-069', 'Sayre Coster', 'diam erat fermentum justo nec condimentum neque sapien');
insert into editorial (clave, nombre, descripcion) values ('51138-055', 'Darcy Cupper', 'consequat varius integer ac leo pellentesque');
insert into editorial (clave, nombre, descripcion) values ('51672-4070', 'Ahmed Hartwell', 'luctus ultricies eu nibh quisque');
insert into editorial (clave, nombre, descripcion) values ('10812-935', 'Simon Troth', 'vel lectus in quam fringilla rhoncus mauris enim');
insert into editorial (clave, nombre, descripcion) values ('49349-996', 'Jacky Janic', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id');
insert into editorial (clave, nombre, descripcion) values ('49121-001', 'Sigmund Bendson', 'porta volutpat quam pede lobortis ligula');
insert into editorial (clave, nombre, descripcion) values ('36987-3143', 'Chelsy Riepl', 'felis eu sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into editorial (clave, nombre, descripcion) values ('64159-6208', 'Burke Rizzelli', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam');
insert into editorial (clave, nombre, descripcion) values ('57896-617', 'Helli D''Cruze', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into editorial (clave, nombre, descripcion) values ('49288-0067', 'Gale Ivanchenkov', 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean');
insert into editorial (clave, nombre, descripcion) values ('42192-138', 'Allyce Boots', 'fusce lacus purus aliquet at feugiat non pretium quis');
insert into editorial (clave, nombre, descripcion) values ('67618-310', 'Cora Scolland', 'magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into editorial (clave, nombre, descripcion) values ('0093-7317', 'Kyle Lauks', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent');
insert into editorial (clave, nombre, descripcion) values ('57520-0242', 'Sarette Dimanche', 'justo lacinia eget tincidunt eget tempus vel pede');
insert into editorial (clave, nombre, descripcion) values ('61715-113', 'Giulia Swindin', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus');
insert into editorial (clave, nombre, descripcion) values ('60681-5302', 'Shellie Langford', 'erat volutpat in congue etiam justo etiam');
insert into editorial (clave, nombre, descripcion) values ('49527-025', 'Federico Rollins', 'eros elementum pellentesque quisque porta volutpat erat quisque erat');
insert into editorial (clave, nombre, descripcion) values ('55154-3677', 'Blondelle Applebee', 'duis aliquam convallis nunc proin at turpis a pede');
insert into editorial (clave, nombre, descripcion) values ('50419-488', 'Melvyn Bloan', 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into editorial (clave, nombre, descripcion) values ('54738-905', 'Eartha St Quenin', 'eu sapien cursus vestibulum proin eu mi');
insert into editorial (clave, nombre, descripcion) values ('63941-473', 'Garret Ilson', 'dapibus duis at velit eu');
insert into editorial (clave, nombre, descripcion) values ('55154-4772', 'Derward Rye', 'sed vestibulum sit amet cursus id');
